spring.application.name=SiteSentinel

server.port=8091

spring.datasource.url=jdbc:postgresql://localhost:5432/sitesentinel_db
spring.datasource.username=postgres
spring.datasource.password=82062544
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration