package com.cigabyte.sitesentinel.recommendation;

public enum RiskRemediationRecommendationValidationIssueCode {

    OUTPUT_REQUIRED,

    SCHEMA_VERSION_REQUIRED,

    SCHEMA_VERSION_MISMATCH,

    TITLE_REQUIRED,

    TITLE_TOO_LONG,

    SUMMARY_REQUIRED,

    SUMMARY_TOO_LONG,

    REMEDIATION_STEPS_REQUIRED,

    REMEDIATION_STEP_REQUIRED,

    REMEDIATION_STEP_TOO_LONG,

    REMEDIATION_STEP_COUNT_EXCEEDED,

    VERIFICATION_STEPS_REQUIRED,

    VERIFICATION_STEP_REQUIRED,

    VERIFICATION_STEP_TOO_LONG,

    VERIFICATION_STEP_COUNT_EXCEEDED,

    ADVISORY_REQUIRED,

    ADVISORY_MUST_BE_TRUE,

    SENSITIVE_CONTENT_DETECTED,

    CONTENT_CONTRACT_VIOLATION
}